apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.name }}
  namespace: {{ .Values.spec.namespace }}
spec:
  selector:
    app: {{ .Release.name }}
  ports:
    - name: client
      port: 2181
      protocol: {{ .Values.service.protocol }}
      targetPort: 2181
    - name: follower
      port: 2888
      protocol: {{ .Values.service.protocol }}
      targetPort: 2888
    - name: leader
      port: 3888
      protocol: {{ .Values.service.protocol }}
      targetPort: 3888
